### ISSUE TITLE
Missing Dependency?

### ISSUE THREAD

**Issue by abravalheri** [corenova/yang-swagger#2]
I am trying to get started with the corenova yang tools for javascript, but after installing yang-swagger (`sudo npm install -g yang-js yang-express yang-swagger`), I got the following error:

```bash
$ yang-swagger amodule.yang
module.js:472
    throw err;
    ^

Error: Cannot find module 'minimist'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/lib/node_modules/yang-swagger/bin/yang-swagger:3:12)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
```

After manually installing `minimist` (`sudo npm install -g minimist`), pyang-swagger runs.

I was wondering: maybe this error is related to a missing dependency on `minimist`...

Did you guys have any idea?

**Comment by sekur** [comment]
@abravalheri - thanks for reporting this, yes I was missing the "minimist" dependency on package.json.  I've added and published a new 1.2.3 version into NPM.
